name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_tree_view: any

dependency_overrides:
  flutter_tree_view:
    git: https://github.com/mbaumgartenbr/flutter_tree_view.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.10.0-nullsafety.3

flutter:
  uses-material-design: true