name: Deploy example to gh-pages

on:
  workflow_dispatch:
  create:

jobs:
  build:
    # Fix for "create" not respecting tags, see https://github.com/actions/runner/issues/1007
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: erickzanardo/flutter-gh-pages@v3
        with:
          workingDir: example